//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPage11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class mobile
    {
        [Display(Name ="MobileID")]
        public int id { get; set; }

        [Display(Name ="Mobile")]
        public string mobile1 { get; set; }
       
        [Display(Name ="Model")]
        public string model { get; set; }
       
        [Display(Name ="Price")]
        public Nullable<decimal> price { get; set; }
       
        [Display(Name ="Description")]
        public string description { get; set; }
    }
}
